"""
app/utils/checksums.py — Fingerprint file parsing + checksum verification.

Background (researched 2026-07-13 against the etree.org wiki and shntool's own
docs, since getting this wrong would be worse than not having the feature):

  .ffp  A "FLAC Fingerprint" is generated by `metaflac --show-md5sum` — it is
        NOT a checksum of the encoded .flac file. It is the MD5 signature FLAC
        itself stores internally, computed over the *decoded* audio samples
        only. Renaming the file or editing tags never changes it. Verifying
        it means reading that signature back out of the file (mutagen already
        exposes it) — no decoding required, so this is fast.

  .st5  shntool's own checksum. Per the etree.org FlacFingerprint page:
        "The flac fingerprint should be identical to what is sometimes called
        a 'shntool md5', which is a checksum calculated on just the music
        data" — i.e. by design, an .st5 value for a given track should equal
        that track's .ffp value. We verify it the same way as ffp. Treated as
        best-effort: shntool is documented to not produce st5 for 24-bit/96k
        FLAC, and we can't rule out edge-case algorithm differences we simply
        don't have visibility into. A mismatch here is worth a second look,
        not an alarm.

  .md5  A conventional whole-file MD5 (hashlib over the raw file bytes,
        including headers/tags). Unlike ffp/st5, this WILL change if Flux (or
        anything else) rewrites the file's Vorbis tags — that's expected
        behavior, not corruption, and the UI should say so.

Nothing here reads audio via librosa/soundfile — ffp/st5 verification only
needs mutagen's already-parsed STREAMINFO, and md5 only needs raw bytes.
"""

import hashlib
import os
import re
import unicodedata

from mutagen.flac import FLAC

_HEX32 = re.compile(r"\b[0-9a-fA-F]{32}\b")
_AUDIO_EXT = re.compile(r"\.(?:flac|wav|shn|mp3)$", re.IGNORECASE)

# Preference order when a folder has more than one fingerprint file covering
# the same track — only one type can occupy a track's checksum_status slot,
# so ties need a winner. ffp first (best-understood format, verifies audio
# content, immune to tag edits), then md5 (whole-file, but simple and well
# understood), then st5 last (verified here by inference from shntool/etree
# docs rather than a spec Ryan's ever actually vetted — see module docstring;
# it shouldn't out-rank a type either of you trusts more). Used by both
# api/ingest.py (_do_confirm) and api/recordings.py (verify_checksums).
FINGERPRINT_TYPE_PRIORITY = {"ffp": 0, "md5": 1, "st5": 2}


def flac_md5_signature(abs_path):
    """The FLAC file's own internal MD5-of-decoded-audio signature, as
    lowercase hex. None if the file can't be read or the encoder never
    stored one (an all-zero signature is valid FLAC for 'not computed')."""
    try:
        info = FLAC(abs_path).info
    except Exception:
        return None
    sig = getattr(info, "md5_signature", 0)
    if not sig:
        return None
    return format(sig, "032x")


def file_md5(abs_path, chunk_size=1024 * 1024):
    """Whole-file MD5, lowercase hex. None if the file can't be read."""
    h = hashlib.md5()
    try:
        with open(abs_path, "rb") as fh:
            for chunk in iter(lambda: fh.read(chunk_size), b""):
                h.update(chunk)
    except OSError:
        return None
    return h.hexdigest()


def parse_checksum_file(content):
    """
    Tolerant line parser for .ffp / .md5 / .st5 text. Community tools don't
    agree on a single delimiter (colon, tab, double-space, "*"-prefixed
    filename...), so rather than commit to one, every line is scanned for a
    32-hex-char token (the checksum) and an audio-filename-shaped token
    (flac/wav/shn/mp3). A line with a hex token but no recognizable filename
    still contributes a checksum — match_entries_to_tracks() falls back to
    positional matching when nothing in the file has a filename.

    Returns: [{"filename": str|None, "checksum": "32charhex"}, ...] in
    file order. Lines with no hex token (blank lines, headers, comments) are
    skipped.
    """
    entries = []
    for line in (content or "").splitlines():
        line = line.strip()
        if not line:
            continue
        hex_match = _HEX32.search(line)
        if not hex_match:
            continue
        checksum = hex_match.group(0).lower()
        # Filename candidate = whatever's left on the line once the hash is
        # cut out, trimmed of the usual separators (*, :, tabs/runs of
        # spaces). Track filenames routinely contain spaces themselves, so
        # this can't be a single-token regex — it has to take "the rest of
        # the line" and just check whether it looks like an audio filename.
        rest = (line[:hex_match.start()] + " " + line[hex_match.end():]).strip(" \t*:")
        filename = os.path.basename(rest) if rest and _AUDIO_EXT.search(rest) else None
        entries.append({"filename": filename, "checksum": checksum})
    return entries


def _norm_key(name):
    """
    NFC-normalize a filename before using it as a comparison key.

    macOS/APFS commonly hands back decomposed (NFD) unicode for filenames
    with accented characters (os.walk, scan_folder), while fingerprint text
    files — usually generated on Windows/Linux, or just typed/pasted — are
    typically composed (NFC). "Lucía" (NFC) and "Lucía" (NFD) are visually
    identical but byte-for-byte different, so a bare string comparison
    silently fails to match. Same failure class the quality-scoring tool hit
    joining disk folder names to DB grades (2026-07-27) — see
    `Context Library/Listening Quality — v2 Results.md`, "Two bugs found."
    Without this, a recording with an accented track title could ingest with
    every checksum unmatched and no error, because match_entries_to_tracks()
    fails closed (leaves rows unmatched) rather than raising.
    """
    return unicodedata.normalize("NFC", name).lower() if name else None


def match_entries_to_tracks(entries, tracks):
    """
    Match parsed fingerprint entries to Track rows. Prefers filename matching
    (exact basename, then filename-stem, both case-insensitive and unicode-
    normalized — a fingerprint generated against the original .shn/.wav set
    will still match the .flac track by stem). Falls back to positional (file
    order == track_number order) ONLY when none of the entries carry a
    filename at all and the counts line up exactly — anything less certain
    is left unmatched rather than guessed.

    Note (2026-07-14): since library audio is now always flattened + renamed
    on ingest (compute_audio_rename_map/move_to_library in app.utils.ingest),
    a fingerprint file lists ORIGINAL scanned filenames while Track.file_path
    holds the new flattened name — filename matching alone won't connect
    them. Confirm-time matching (app.api.ingest._do_confirm) handles this
    with a proxy that presents each track's original filename here instead
    of its real one; this function's matching logic is unchanged and stays
    strict on purpose — see [[project_checksum_format_preference]].

    Returns: {track: checksum} for whatever could be confidently matched.
    """
    if not entries or not tracks:
        return {}

    def _stem(name):
        return os.path.splitext(name)[0].lower() if name else None

    by_basename = {_norm_key(os.path.basename(t.file_path)): t for t in tracks}
    by_stem     = {_norm_key(_stem(t.file_path)): t for t in tracks}

    matched = {}
    named_entries = [e for e in entries if e["filename"]]

    for e in named_entries:
        key = _norm_key(e["filename"])
        track = by_basename.get(key) or by_stem.get(_norm_key(_stem(e["filename"])))
        if track and track not in matched:
            matched[track] = e["checksum"]

    if not named_entries and len(entries) == len(tracks):
        ordered_tracks = sorted(tracks, key=lambda t: t.track_number)
        for track, e in zip(ordered_tracks, entries):
            matched[track] = e["checksum"]

    return matched


def discover_fingerprint_files(folder_abs_path):
    """
    Walk an already-ingested recording's library folder for fingerprint files
    that were copied in with it but never parsed — either because it was
    ingested before this feature existed, or the folder held one the initial
    scan missed. `move_to_library` copies the entire source tree (not just
    audio), so anything that shipped alongside the show is still sitting
    right there. Reuses the same marker-based detection as scan_folder() so a
    recording processed this way is classified identically to a fresh ingest.

    Returns: [{"type", "filename", "rel_path"}, ...]
    """
    # Imported lazily to avoid a module-load-order dependency between the two
    # utils modules — app/api/ingest.py already imports both directly.
    from app.utils.ingest import FINGERPRINT_MARKERS, AUDIO_EXTENSIONS, _detect_fp_type

    found = []
    for dirpath, _dirnames, filenames in os.walk(folder_abs_path):
        for fname in filenames:
            ext = os.path.splitext(fname)[1].lower()
            if ext in AUDIO_EXTENSIONS:
                continue
            low = fname.lower()
            if any(m in low for m in FINGERPRINT_MARKERS):
                full = os.path.join(dirpath, fname)
                found.append({
                    "type":     _detect_fp_type(low),
                    "filename": fname,
                    "rel_path": os.path.relpath(full, folder_abs_path),
                })
    return found


def verify_track_checksum(abs_path, fp_type, expected_checksum):
    """Recompute a track's actual checksum and compare. Returns one of
    'match' / 'mismatch' / 'unverified' (couldn't compute — missing file,
    unreadable FLAC, or no expected value to compare against)."""
    if not expected_checksum:
        return "unverified"
    if fp_type in ("ffp", "st5"):
        actual = flac_md5_signature(abs_path)
    elif fp_type == "md5":
        actual = file_md5(abs_path)
    else:
        actual = None
    if not actual:
        return "unverified"
    return "match" if actual.lower() == expected_checksum.strip().lower() else "mismatch"
